const images = [
    {
        id: 1,
        src: 'assets/cat.jpg',
        name: 'Cat',
        category: 'Animals',
        dateadded: new Date("2024-01-05"),
    },
    {
        id: 2,
        src: 'assets/Chameleon.jpg',
        name: 'Chameleon',
        category: 'Animals',
        dateadded: new Date("2024-01-02"),
    },
    {
        id: 3,
        src: 'assets/cheetah.jpg',
        name: 'Cheetah',
        category: 'Animals',
        dateadded: new Date("2024-01-08"),
    },
    {
        id: 4,
        src: 'assets/DOg.jpg',
        name: 'Dog',
        category: 'Animals',
        dateadded: new Date("2024-01-12"),
    },
    {
        id: 5,
        src: 'assets/fox.jpg',
        name: 'Fox',
        category: 'Animals',
        dateadded: new Date("2024-01-10"),
    },
    {
        id: 6,
        src: 'assets/Giraffee.jpg',
        name: 'Giraffe',
        category: 'Animals',
        dateadded: new Date("2024-01-07"),
    },
    {
        id: 7,
        src: 'assets/hedgehog.jpg',
        name: 'Hedgehog',
        category: 'Animals',
        dateadded: new Date("2024-01-09"),
    },
    {
        id: 8,
        src: 'assets/iguana.jpg',
        name: 'Iguana',
        category: 'Animals',
        dateadded: new Date("2024-03-11"),
    },
    {
        id: 9,
        src: 'assets/meerkat.jpg',
        name: 'Meerkat',
        category: 'Animals',
        dateadded: new Date("2024-04-03"),
    },
    {
        id: 10,
        src: 'assets/parrot.jpg',
        name: 'Parrot',
        category: 'Animals',
        dateadded: new Date("2024-05-06"),
    },
    {
        id: 11,
        src: 'assets/peacock.jpg',
        name: 'Peacock',
        category: 'Animals',
        dateadded: new Date("2024-06-08"),
    },
    {
        id: 12,
        src: 'assets/snake.jpg',
        name: 'Snake',
        category: 'Animals',
        dateadded: new Date("2023-07-09"),
    },
    {
        id: 13,
        src: 'assets/squirrel.jpg',
        name: 'Squirrel',
        category: 'Animals',
        dateadded: new Date("2024-05-10"),
    },
    {
        id: 14,
        src: 'assets/tamarin.jpg',
        name: 'Tamarin',
        category: 'Animals',
        dateadded: new Date("2024-04-11"),
    },
    {
        id: 15,
        src: 'assets/tiger.jpg',
        name: 'Tiger',
        category: 'Animals',
        dateadded: new Date("2024-06-18"),
    },
    {
        id: 16,
        src: 'assets/zebra.jpg',
        name: 'Zebra',
        category: 'Animals',
        dateadded: new Date("2023-08-19"),
    },
    {
        id: 17,
        src: 'assets/apple.jpg',
        name: 'Apple',
        category: 'Fruits',
        dateadded: new Date("2023-09-23"),
    },
    {
        id: 18,
        src: 'assets/banana.jpg',
        name: 'Banana',
        category: 'Fruits',
        dateadded: new Date("2023-10-25"),
    },
    {
        id: 19,
        src: 'assets/carrot.jpg',
        name: 'Carrot',
        category: 'Vegetables',
        dateadded: new Date("2023-11-27"),
    },
    {
        id: 20,
        src: 'assets/lime.jpg',
        name: 'Lime',
        category: 'Fruits',
        dateadded: new Date("2023-12-29"),
    },
    {
        id: 21,
        src: 'assets/orange.jpg',
        name: 'Orange',
        category: 'Fruits',
        dateadded: new Date("2024-01-30"),
    },
    {
        id: 22,
        src: 'assets/pineapple.jpg',
        name: 'Pineapple',
        category: 'Fruits',
        dateadded: new Date("2024-03-31"),
    },
    {
        id: 23,
        src: 'assets/strawberry.jpg',
        name: 'Strawberry',
        category: 'Fruits',
        dateadded: new Date("2024-03-01"),
    },
    {
        id: 24,
        src: 'assets/watermelon.jpg',
        name: 'Watermelon',
        category: 'Fruits',
        dateadded: new Date("2024-02-02"),
    },
    {
        id: 25,
        src: 'assets/camera.jpg',
        name: 'Camera',
        category: 'Electronics',
        dateadded: new Date("2024-01-03"),
    },
    {
        id: 26,
        src: 'assets/computers.jpg',
        name: 'Computers',
        category: 'Electronics',
        dateadded: new Date("2024-01-04"),
    },
    {
        id: 27,
        src: 'assets/controller.jpg',
        name: 'Controller',
        category: 'Electronics',
        dateadded: new Date("2024-05-05")
    },
    {
        id: 28,
        src: 'assets/headset.jpg',
        name: 'Headset',
        category: 'Electronics',
        dateadded: new Date("2024-06-06"),
    },
    {
        id: 29,
        src: 'assets/laptop.jpg',
        name: 'Laptop',
        category: 'Electronics',
        dateadded: new Date("2023-07-07"),
    },
    {
        id: 30,
        src: 'assets/mobilephone.jpg',
        name: 'Mobilephone',
        category: 'Electronics',
        dateadded: new Date("2023-08-08"),
    },
    {
        id: 31,
        src: 'assets/peas.jpg',
        name: 'Peas',
        category: 'Vegetables',
        dateadded: new Date("2023-09-09"),
    },
    {
        id: 32,
        src: 'assets/tomato.jpg',
        name: 'Tomato',
        category: 'Vegetables',
        dateadded: new Date("2023-10-10"),
    },
    
]

export default images;